package com.teadelivery.user.guest.service;

import com.teadelivery.user.guest.dto.GuestUserRequest;
import com.teadelivery.user.guest.dto.GuestUserResponse;
import com.teadelivery.user.guest.dto.GuestSessionResponse;
import com.teadelivery.user.guest.model.GuestUser;
import com.teadelivery.user.guest.repository.GuestUserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for GuestUserService.
 * Follows coding standards with comprehensive test coverage.
 */
@ExtendWith(MockitoExtension.class)
class GuestUserServiceTest {

    @Mock
    private GuestUserRepository guestUserRepository;

    @Mock
    private DeviceFingerprintService deviceFingerprintService;

    @InjectMocks
    private GuestUserService guestUserService;

    private GuestUserRequest validGuestRequest;
    private GuestUser mockGuestUser;

    @BeforeEach
    void setUp() {
        validGuestRequest = GuestUserRequest.builder()
                .deviceId("device_123456789")
                .userAgent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)")
                .ipAddress("192.168.1.100")
                .sessionMetadata(GuestUserRequest.SessionMetadata.builder()
                        .platform("web")
                        .version("1.0.0")
                        .build())
                .build();

        mockGuestUser = GuestUser.builder()
                .id(UUID.randomUUID())
                .deviceId("device_123456789")
                .sessionToken("session_token_123")
                .expiresAt(LocalDateTime.now().plusHours(24))
                .actionCount(0)
                .conversionPromptsShown(0)
                .isActive(true)
                .build();
    }

    @Test
    @DisplayName("Should create guest user successfully")
    void shouldCreateGuestUserSuccessfully() {
        // Given
        when(deviceFingerprintService.isValidDeviceId(validGuestRequest.getDeviceId())).thenReturn(true);
        when(guestUserRepository.existsActiveByDeviceId(anyString(), any(LocalDateTime.class))).thenReturn(false);
        when(guestUserRepository.findByDeviceIdAndCreatedAtAfter(anyString(), any(LocalDateTime.class))).thenReturn(List.of());
        when(guestUserRepository.save(any(GuestUser.class))).thenAnswer(invocation -> {
            GuestUser savedUser = invocation.getArgument(0);
            // Set the ID as if it was generated by the database
            savedUser.setId(mockGuestUser.getId());
            return savedUser;
        });

        // When
        GuestUserResponse response = guestUserService.createGuestUser(validGuestRequest);

        // Then
        assertThat(response.isSuccess()).isTrue();
        assertThat(response.getMessage()).isEqualTo("Guest account created");
        assertThat(response.getData()).isNotNull();
        assertThat(response.getData().getGuestUserId()).isEqualTo(mockGuestUser.getId().toString());
        assertThat(response.getData().getUserType()).isEqualTo("GUEST");
        assertThat(response.getData().getLimitations()).hasSize(5);

        verify(deviceFingerprintService).isValidDeviceId(validGuestRequest.getDeviceId());
        verify(guestUserRepository).existsActiveByDeviceId(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).save(any(GuestUser.class));
    }

    @Test
    @DisplayName("Should reject invalid device ID")
    void shouldRejectInvalidDeviceId() {
        // Given
        when(deviceFingerprintService.isValidDeviceId(validGuestRequest.getDeviceId())).thenReturn(false);

        // When
        GuestUserResponse response = guestUserService.createGuestUser(validGuestRequest);

        // Then
        assertThat(response.isSuccess()).isFalse();
        assertThat(response.getMessage()).isEqualTo("Invalid device identifier");

        verify(deviceFingerprintService).isValidDeviceId(validGuestRequest.getDeviceId());
        verifyNoInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should reject when device already has active session")
    void shouldRejectWhenDeviceHasActiveSession() {
        // Given
        when(deviceFingerprintService.isValidDeviceId(validGuestRequest.getDeviceId())).thenReturn(true);
        when(guestUserRepository.existsActiveByDeviceId(anyString(), any(LocalDateTime.class))).thenReturn(true);

        // When
        GuestUserResponse response = guestUserService.createGuestUser(validGuestRequest);

        // Then
        assertThat(response.isSuccess()).isFalse();
        assertThat(response.getMessage()).isEqualTo("Device already has an active guest session");

        verify(deviceFingerprintService).isValidDeviceId(validGuestRequest.getDeviceId());
        verify(guestUserRepository).existsActiveByDeviceId(anyString(), any(LocalDateTime.class));
        verifyNoMoreInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should reject when daily limit exceeded")
    void shouldRejectWhenDailyLimitExceeded() {
        // Given
        when(deviceFingerprintService.isValidDeviceId(validGuestRequest.getDeviceId())).thenReturn(true);
        when(guestUserRepository.existsActiveByDeviceId(anyString(), any(LocalDateTime.class))).thenReturn(false);
        when(guestUserRepository.findByDeviceIdAndCreatedAtAfter(anyString(), any(LocalDateTime.class)))
                .thenReturn(List.of(mockGuestUser, mockGuestUser, mockGuestUser));

        // When
        GuestUserResponse response = guestUserService.createGuestUser(validGuestRequest);

        // Then
        assertThat(response.isSuccess()).isFalse();
        assertThat(response.getMessage()).isEqualTo("Daily guest session limit exceeded. Please register for full access.");

        verify(deviceFingerprintService).isValidDeviceId(validGuestRequest.getDeviceId());
        verify(guestUserRepository).existsActiveByDeviceId(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).findByDeviceIdAndCreatedAtAfter(anyString(), any(LocalDateTime.class));
        verifyNoMoreInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should get guest session successfully")
    void shouldGetGuestSessionSuccessfully() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(mockGuestUser));
        when(guestUserRepository.save(any(GuestUser.class))).thenReturn(mockGuestUser);

        // When
        GuestSessionResponse response = guestUserService.getGuestSession("valid_session_token");

        // Then
        assertThat(response.isSuccess()).isTrue();
        assertThat(response.getMessage()).isEqualTo("Guest session info retrieved");
        assertThat(response.getData()).isNotNull();
        assertThat(response.getData().getGuestUserId()).isEqualTo(mockGuestUser.getId().toString());
        assertThat(response.getData().getSessionStatus()).isEqualTo("active");
        assertThat(response.getData().getLimitations()).hasSize(5);

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).save(any(GuestUser.class));
    }

    @Test
    @DisplayName("Should reject invalid session token")
    void shouldRejectInvalidSessionToken() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.empty());

        // When
        GuestSessionResponse response = guestUserService.getGuestSession("invalid_session_token");

        // Then
        assertThat(response.isSuccess()).isFalse();
        assertThat(response.getMessage()).isEqualTo("Invalid or expired session");

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verifyNoMoreInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should record guest action successfully")
    void shouldRecordGuestActionSuccessfully() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(mockGuestUser));
        when(guestUserRepository.save(any(GuestUser.class))).thenReturn(mockGuestUser);

        // When
        boolean shouldShowPrompt = guestUserService.recordGuestAction("valid_session_token");

        // Then
        assertThat(shouldShowPrompt).isFalse(); // Action count is 0, threshold is 5

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).save(any(GuestUser.class));
    }

    @Test
    @DisplayName("Should trigger conversion prompt after 5 actions")
    void shouldTriggerConversionPromptAfterFiveActions() {
        // Given
        GuestUser guestWithActions = GuestUser.builder()
                .id(mockGuestUser.getId())
                .deviceId(mockGuestUser.getDeviceId())
                .sessionToken(mockGuestUser.getSessionToken())
                .expiresAt(mockGuestUser.getExpiresAt())
                .actionCount(4)
                .conversionPromptsShown(mockGuestUser.getConversionPromptsShown())
                .isActive(mockGuestUser.getIsActive())
                .build();
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(guestWithActions));
        when(guestUserRepository.save(any(GuestUser.class))).thenReturn(guestWithActions);

        // When
        boolean shouldShowPrompt = guestUserService.recordGuestAction("valid_session_token");

        // Then
        assertThat(shouldShowPrompt).isTrue(); // Action count becomes 5, threshold is 5

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).save(any(GuestUser.class));
    }

    @Test
    @DisplayName("Should reject action recording for invalid session")
    void shouldRejectActionRecordingForInvalidSession() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.empty());

        // When
        boolean shouldShowPrompt = guestUserService.recordGuestAction("invalid_session_token");

        // Then
        assertThat(shouldShowPrompt).isFalse();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verifyNoMoreInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should record conversion prompt shown successfully")
    void shouldRecordConversionPromptShownSuccessfully() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(mockGuestUser));
        when(guestUserRepository.save(any(GuestUser.class))).thenReturn(mockGuestUser);

        // When
        boolean recorded = guestUserService.recordConversionPromptShown("valid_session_token");

        // Then
        assertThat(recorded).isTrue();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verify(guestUserRepository).save(any(GuestUser.class));
    }

    @Test
    @DisplayName("Should reject conversion prompt recording for invalid session")
    void shouldRejectConversionPromptRecordingForInvalidSession() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.empty());

        // When
        boolean recorded = guestUserService.recordConversionPromptShown("invalid_session_token");

        // Then
        assertThat(recorded).isFalse();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
        verifyNoMoreInteractions(guestUserRepository);
    }

    @Test
    @DisplayName("Should validate guest session successfully")
    void shouldValidateGuestSessionSuccessfully() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(mockGuestUser));

        // When
        boolean isValid = guestUserService.isValidGuestSession("valid_session_token");

        // Then
        assertThat(isValid).isTrue();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
    }

    @Test
    @DisplayName("Should reject invalid guest session")
    void shouldRejectInvalidGuestSession() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.empty());

        // When
        boolean isValid = guestUserService.isValidGuestSession("invalid_session_token");

        // Then
        assertThat(isValid).isFalse();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
    }

    @Test
    @DisplayName("Should get guest user by session token successfully")
    void shouldGetGuestUserBySessionTokenSuccessfully() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.of(mockGuestUser));

        // When
        Optional<GuestUser> guestUser = guestUserService.getGuestUserBySessionToken("valid_session_token");

        // Then
        assertThat(guestUser).isPresent();
        assertThat(guestUser.get().getId()).isEqualTo(mockGuestUser.getId());

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
    }

    @Test
    @DisplayName("Should return empty for invalid session token")
    void shouldReturnEmptyForInvalidSessionToken() {
        // Given
        when(guestUserRepository.findActiveBySessionToken(anyString(), any(LocalDateTime.class)))
                .thenReturn(Optional.empty());

        // When
        Optional<GuestUser> guestUser = guestUserService.getGuestUserBySessionToken("invalid_session_token");

        // Then
        assertThat(guestUser).isEmpty();

        verify(guestUserRepository).findActiveBySessionToken(anyString(), any(LocalDateTime.class));
    }
} 