global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'microservices'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - 'tea-snacks-user-management:8080'
        - 'tea-snacks-order-catalog:8080'
        - 'tea-snacks-payment-management:8080'
        - 'tea-snacks-delivery-management:8080'
        - 'tea-snacks-notification:8080'
        - 'tea-snacks-search-discovery:8080'
