dependencies {
    implementation project(':shared:common')
    
    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    
    // Elasticsearch
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    
    // Cache
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    
    // Messaging
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-actuator-autoconfigure'
}

bootJar {
    enabled = true
}

jar {
    enabled = false
} 